[package]
name = "dalang"
description = "A web-based server-based video editor"
version = "0.1.0"
edition = "2021"

[lib]
name = "dalang_server"
path = "src/dalang_server/lib.rs"

[[bin]]
name = "dalang"
test = false
doc = false

[dependencies]
clap = { version = "^4.1.4", features = ["cargo"] }
